.PHONY: all snake slider bad-apple

all: snake slider bad-apple

snake:
	@echo "========== Building snake =========="
	@(cd snake && make)

slider:
	@echo "========== Building slider =========="
	@(cd slider && make)

bad-apple:
	@echo "========== Building bad-apple =========="
	@(cd bad-apple && make)